name: hello-world
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: install-requirements
        run: pwd
      - name: install-requirements2
        run: ls
      - name: install-requirements3
        run: cd ..
      - name: install-requirements4
        run: pwd
      - name: install-requirements5
        run: ls
